os: linux
language: rust
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
env:
  - RUST_BACKTRACE=full
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
before_script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      cargo install cargo-tarpaulin  
      rustup component add clippy
      rustup component add rustfmt
    else
      rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      rustup component add rustfmt --toolchain nightly || cargo install --git https://github.com/rust-lang/rustfmt/ --force fmt
    fi
script:
  - cargo fmt -- --check
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      USE_SKEPTIC=1 cargo tarpaulin --out Xml && bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"
    else
      cargo test --all
    fi
  - cargo clippy --all-targets --tests -- -D clippy::pedantic
